# Generated by Django 3.0.6 on 2022-04-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oddam_w_dobre_rece_app', '0002_donation_institution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='adress',
            new_name='address',
        ),
    ]
